### ISSUE TITLE
Can't install on arch via AUR

### ISSUE THREAD

**Issue by SKProCH** [vyvir/althea#10]
Hello, the https://aur.archlinux.org/packages/altlinux as specified in README not available.  
Also, i can't install `altlinux-git` due to this error while trying to install it via `yay`:
```
==> Starting prepare()...
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: altlinux-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
altlinux-git - exit status 4
```

**Comment by Renen12** [comment]
I also have this issue

**Comment by vindeckyy** [comment]
It seems like you're encountering issues while trying to install altlinux-git using yay on Arch Linux. The error message indicates an externally managed environment and suggests using specific commands to manage Python packages. Try this:

Open a terminal.
Run the following command to install python-pipx:

sudo pacman -S python-pipx

Once python-pipx is installed, use the following command to install altlinux-git:

pipx install altlinux-git

This will create a virtual environment and manage the installation of altlinux-git within that environment.
Follow the prompts and confirm the installation when prompted.
Once the installation is complete, you should be able to use altlinux-git as intended.
By using pipx, you can create a separate virtual environment for the installation of altlinux-git and ensure that it doesn't interfere with your system's Python installation.

**Comment by SKProCH** [comment]
pipx can't locate package (i suppose cuz its a pacman package, not an python package). Here is the output:
```
Fatal error from pip prevented installation. Full pip output in file:
    /home/skproch/.local/pipx/logs/cmd_2023-07-07_14.43.57_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Could not find a version that satisfies the requirement altlinux-git (from versions: none)
    ERROR: No matching distribution found for altlinux-git

Error installing altlinux-git.
```
Log file content:
```
PIP STDOUT
----------

PIP STDERR
----------
ERROR: Could not find a version that satisfies the requirement altlinux-git (from versions: none)
ERROR: No matching distribution found for altlinux-git
```

**Comment by PaPerseller** [comment]
sucessful installed by remove file /usr/lib/python3.11/EXTERNALLY-MANAGED

**Comment by vyvir** [comment]
Hi, the AUR package is not maintained by us, so we can't help resolve the issue
Please contact the AUR maintainer instead
