### ISSUE TITLE
AltLinux is unable to connect to the internet

### ISSUE THREAD

**Issue by cankurttekin** [vyvir/althea#18]
Hello, when i start application i get an error saying;
"AltLinux is unable to connect to the internet. Please connect to the internet and restart AltLinux."

Pop!_OS 22.04 LTS

**Comment by vyvir** [comment]
Could you start AltLinux from terminal and show the output?

**Comment by vyvir** [comment]
Hi! Try the latest version of AltLinux and report if the issue still persists.

**Comment by cankurttekin** [comment]
hey i cant report back, thankfully i no longer have access to ipad or ios anymore.

**Comment by jamiejackherer** [comment]
I'm having this same problem. Installed AltLinux from AUR and everything went perfectly well. But when I try to run the application, I get a pop up stating "AltLinux is unable to connect to the internet. Please connect to the internet and restart AltLinux." 

Of course, I have a good internet connection. Running AltLinux from the terminal gives nothing strange.

**Comment by jamiejackherer** [comment]
I've found the problem.. 

In the file `main.py` the function `connectioncheck()` tries to check if the internet is working by using `urlopen` with the URL `http://www.example.com` which returns false. 

Changing this URL to `https://www.google.com` fixed this issue.

**Comment by vyvir** [comment]
> I've found the problem..
> 
> In the file `main.py` the function `connectioncheck()` tries to check if the internet is working by using `urlopen` with the URL `http://www.example.com` which returns false.
> 
> Changing this URL to `https://www.google.com` fixed this issue.

Hi, could you check if `https://www.example.com` works for you?

**Comment by vyvir** [comment]
Assuming this issue has been fixed, closing
