### ISSUE TITLE
Does not load on Ubuntu 22.04.4 LTS

### ISSUE THREAD

**Issue by nighto** [vyvir/althea#22]
After installing the package and its dependencies, trying to load AltLinux from the menu doesn't do anything (no window appears etc).

Trying to run it from the terminal, it gives this error:

```
$ /usr/lib/altlinux/altlinux 

(altlinux:57619): GLib-GIO-ERROR **: 16:46:03.914: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap (core dumped)
```

**Comment by vyvir** [comment]
Hi! Try the latest version of AltLinux and report if the issue still persists.

**Comment by vyvir** [comment]
Your gsettings schema is broken. 
Check the latest post here for a possible solution: https://gitlab.gnome.org/GNOME/gtk/-/issues/3680
