### ISSUE TITLE
Can't log in inside AltStore

### ISSUE THREAD

**Issue by RayJW** [vyvir/althea#29]
Once I installed AltStore and successfully paired the device, I always get the following error when I try to log in to my Apple ID.

> Started wired server connection!
> Receiving request size...
> Receiving 48 bytes...
> Received response status code: 502
> parse anisette data ret
> Represented Value: 317
> Failed to handle request:Incorrect Content-Type: must be textual to extract_string, JSON to extract_json.

**Comment by vyvir** [comment]
Try the script version and report the issue if it still persists. The deb is no longer supported.

**Comment by RayJW** [comment]
This was with the script method. That error occurred on Arch Linux, just ran it straight from the git clone in a venv, no deb install. I will try on my other machine with Fedora and report back whether there is anything different.

**Comment by vyvir** [comment]
> Also, I think the CPU detection is broken. It told me the CPU isn't supported on both devices, one running AMD Ryzen and the other one Intel 12th gen. So both obviously x86.

fixed cpu detection, try latest

**Comment by vyvir** [comment]
also remove the altlinux folder from $HOME/.local/share

**Comment by RayJW** [comment]
CPU detection works now, the other issue still persists.

> SSeenntt  wwiirreedd  sseerrvveerr  ccoonnnneeccttiioonn  aavvaaiillaabbllee  rreessppoonnssee!!
> 
> Started wired sSetravretre dc owninreecdt isoenr!v
> er cReceiving request size...o
> nnection!
> Receiving request size...
> Receiving 48 bytes...
> Received response status code: 502
> parse anisette data ret
> Represented Value: 317
> Failed to handle request:Incorrect Content-Type: must be textual to extract_string, JSON to extract_json.

**Comment by NicolaiVdS** [comment]
> also remove the altlinux folder from $HOME/.local/share

did that and used the git version and still the same issue

**Comment by WerIstLuka** [comment]
same problem on linux mint 21.3

```
Started wired server connection!
Receiving request size...
Receiving 48 bytes...
Received response status code: 502
parse anisette data ret
Represented Value: 317
Failed to handle request:Incorrect Content-Type: must be textual to extract_string, JSON to extract_json.
```

i use the git version

**Comment by vyvir** [comment]
Hi, try the latest version to see if the issue persists

**Comment by hypackel** [comment]
same problem on debian

**Comment by hypackel** [comment]
reinstalling seemed to work but now when trying to install an ipa, it says

`Failed to handle request:Incorrect Content-Type: must be textual to extract_string, JSON to extract_json.`

**Comment by RayJW** [comment]
> reinstalling seemed to work but now when trying to install an ipa, it says
> 
> `Failed to handle request:Incorrect Content-Type: must be textual to extract_string, JSON to extract_json.`

I can confirm this. The same on my end.

**Comment by vyvir** [comment]
Please try the latest update and report back if the issue still persists.

**Comment by RayJW** [comment]
I can confirm this issue is now fixed! :)
