### ISSUE TITLE
Can't log into the Alt Store

### ISSUE THREAD

**Issue by JoBergeron** [vyvir/althea#30]
Running Mint 22 and I get the following message when attempting to install the Altstore app

AltServer has failed
Registering device...
Received response status code: 200
Fetching certificate...
Alert: Could not install AltStore.ipa to unknown.
Request canceled by user.
Press any key to continue...

**Comment by vyvir** [comment]
Try the script version and report the issue if it still persists. The deb is no longer supported.

**Comment by vyvir** [comment]
remove the altlinux folder from $HOME/.local/share and try latest script version

**Comment by vyvir** [comment]
Duplicate of https://github.com/vyvir/althea/issues/29
