### ISSUE TITLE
WARNING Error:

### ISSUE THREAD

**Issue by csdamien** [vyvir/althea#32]
*** WARNING *** The program 'python3.12' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
DNSServiceRegister result: 0

I amn on Manjaro and get this error when I run Althea, how can I fix it please ?

**Comment by UpstairsSwimmer** [comment]
(using arch btw) I had the same "issue." check the system tray, it probably works regardless of the error.

**Comment by csdamien** [comment]
Oh I hadn’t seen thanks!
