### ISSUE TITLE
Unable to refresh AltServer, sideload apps, sign in, etc.

### ISSUE THREAD

**Issue by queben** [vyvir/althea#37]
Upon using the Git method provided in the guide of getting the server set up, I'm able to get AltStore installed on my iPhone, but not able to get any refreshes, apps installed, or even able to sign in to my developer account to start using AltStore. 

Have tried both wired and wireless when trying to do any of the above. I was only able to get signed into my developer account when I switched to LTE. Refreshing and app installs fail on wired/wireless. Terminal for AltServer shows action happening, but ends up saying "Failed to handle request: Incorrect Content-Type: must be textual to extract_string, JSON to extract_json)."

Here's an example of some of the errors

![image](https://github.com/user-attachments/assets/917c0b06-8bf5-4af9-9f14-810acb8af8e7)

**Comment by vyvir** [comment]
Please try the latest update and report back if the issue still persists.
