### ISSUE TITLE
File "/home/(user)/althea/main.py", line 4, in <module>

### ISSUE THREAD

**Issue by jpedrothejo** [vyvir/althea#41]
This error occurs to me when I run python3 main.py on Fedora 41 with KDE. Seems to work after I delete that line tho.

full error:
  File "/home/(user)/althea/main.py", line 4, in <module>
    from re import T
ImportError: cannot import name 'T' from 're' (/usr/lib64/python3.13/re/__init__.py) 
![image](https://github.com/user-attachments/assets/76967a51-9117-4002-927e-5ea874071ceb)

also I can't seem to pair it
![Screenshot_20241105_212135](https://github.com/user-attachments/assets/b87494c1-3e7e-4ac7-84f2-f171b5503e44)

**Comment by vyvir** [comment]
Should be fine now; Check the latest update

**Comment by vyvir** [comment]
I don't know about that pairing error though, maybe try a different cable?

**Comment by vyvir** [comment]
Nevermind, this is related to libimobiledevice and its packaging in Fedora 41.

You can downgrade crypto policies to the previous Fedora version:
`sudo update-crypto-policies --set FEDORA40`

https://bugzilla.redhat.com/show_bug.cgi?id=2321958

**Comment by jpedrothejo** [comment]
i just found out the pairing code thing is openssl related ig sooo
