### ISSUE TITLE
It takes older version of altserver which has provision issue

### ISSUE THREAD

**Issue by csc-chicken** [vyvir/althea#8]
It installs altserver 1.6.b2, while  windows installs altserver 1.6.3 . We need newer version to solve provision issue thanks

**Comment by yourfriendoss** [comment]
i think you're mixing up something - 1.6.b2 is an altstore version. altserver is as updated as we can get it - it seems that the development of altserver-windows (which altserver-linux, and therefor this project is dependent on) has stopped, we cannot do anything about it.

HOWEVER, Altstore was updated to 1.6.3 and no longer uses betas in AltLinux1. 

Please try again, or clarify what you mean. Thank you.

**Comment by vyvir** [comment]
Hi! Try the latest version of AltLinux and report if the issue still persists.
